APPLICATION_NAME = "Escortefans"
APPLICATION_SLOGAN = "Passez des bons moments!"
APPLICATION_DESCRIPTION = "Le plus grand réseau d'escorte girls et escorte boy au Monde."
APPLICATION_KEYWORDS = []
SEX = [["Femme"], ["Homme"]]
MARITAL_STATUS = [["Célibataire"], ["Marié(e)"], ["Divorcé(e)"], ["Veuve"], ["Veuf"]]
SEXUAL_ORIENTATION = [["Hétéro-sexuel(le)"], ["Homo-sexuel(le)"], ["Bi-sexuel(le)"]]
PURPOSES = [["Flirt"], ["Sexe"]]
AVAILABILITY = [["Oui"], ["Non"]]
CORPULENCES = [["Mince"], ["Athlétique"], ["Plutôt bien"], ["Musclé"], ["Proportionnel à ma taille"], ["Avec des petites rondeurs"], ["Taille forte"], ["Handicapé"]]
HAIR_TYPES = [["Bruns"], ["Noirs"], ["Blonds"], ["Roux"], ["Châtains"], ["Plusieurs couleurs"], ["Autre couleur"], ["Poivre et sel"], ["Blancs"], ["Chauve ou rasé"]]
EYE_TYPES = [["Bleus"],["Verts"], ["Pers"], ["Bruns"], ["Noisettes"], ["Marrons"]]
